server:
  #隧道id:fc22a8ffba327d1d
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam_store?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Wxllgy99
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /templates/
      suffix: .html